core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('gestion_contraloria.urls')),
    path('', include('plantilla.urls')),
]

plantilla/urls.py
from django.urls import path
from .views import IndexView

app_name = 'plantilla'
urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

user/urls.py
from django.urls import path, include
from .views import *

app_name = 'user'
urlpatterns = [
    path('login/', UsersLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UsersLoginView.as_view(), name='profile'),
    path('segurity/', UsersLoginView.as_view(), name='segurity'),
    path('edit_profile/', UsersLoginView.as_view(), name='edit_profile'),
]

plantilla/models.py
from django.db import models

# Create your models here.

plantilla/views.py
from django.views.generic import TemplateView

class IndexView(TemplateView):

    template_name = 'index.html'

plantilla/templates/base/body.html
{% load static %}
{% block head %}
    {% include 'base/head.html' %}
{% endblock  %}
<body class="hold-transition sidebar-mini">

    {% block header %}
        {% include 'base/header.html' %}
    {% endblock  %}
    
 
  
    {% block content %}
    {% endblock content %}
   
   
    {% block footer %}
        {% include 'base/footer.html' %}
    {% endblock  %}

    {% block scripts %}
        {% include 'base/scripts_alert.html' %}
    {% endblock  %}

</body>

plantilla/templates/base/footer.html
{% load static %}

<footer role="contentinfo" class="footer bg-blue">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
                <div class="region region-footer-branding">

                    <div class="views-element-container block block-views block-views-blockultima-actualizacion-block-1" id="block-views-block-ultima-actualizacion-block-1">
                        <h2>Última actualización</h2>
                        <div>
                            <div class="view view-ultima-actualizacion view-id-ultima_actualizacion view-display-id-block_1 js-view-dom-id-b624d1a5a802d96693528a279fab592479abcaa703f60e3d62bd0349ab377378">
                                <div class="view-content">
                                    <div class="views-row">
                                        <div class="views-field views-field-changed">
                                            <span class="field-content">28/06/2024 - 08:32</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <nav role="navigation" aria-labelledby="block-menuredessociales-2-menu" id="block-menuredessociales-2" class="block block-menu navigation menu--menu-redes-sociales">
                        <h2 id="block-menuredessociales-2-menu">Síganos en</h2>
                        <ul class="menu">
                            <li class="menu-item">
                                <a href="https://www.facebook.com/ContraloriaCuba" class="facebook" target="_blank" title="Facebook">Facebook</a>
                            </li>
                            <li class="menu-item">
                                <a href="https://twitter.com/ContraloriaCuba" class="twitter" target="_blank" title="Twitter">Twitter</a>
                            </li>
                            <li class="menu-item">
                                <a href="https://www.youtube.com/channel/UCN41MtbAoBojy9uSldH3BUg" class="youtube" target="_blank" title="Youtube">Youtube</a>
                            </li>
                            <li class="menu-item">
                                <a href="https://www.picta.cu/canal/Contralor%C3%ADa_General_de_la_Rep%C3%BAblica_de_Cuba" class="picta" target="_blank" title="Picta">Picta</a>
                            </li>
                            <li class="menu-item">
                                <a href="https://www.instagram.com/contraloriacuba/?hl=es-la" class="instagram" target="_blank" title="Instagram">Instagram</a>
                            </li>
                            <li class="menu-item">
                                <a href="https://t.me/Contraloria_General_Cuba" class="telegram" target="_blank">Telegram</a>
                            </li>
                            <li class="menu-item">
                                <a href="/rss.xml" class="rss" target="_blank" data-drupal-link-system-path="rss.xml" title="RSS">RSS</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="row justify-content-center col-12">
                <div>
                    <h2>Enlaces de interés</h2>
                </div>
                <div class="row justify-content-center">
                    <div class="container col-3">
                        <a href="/" rel="home" class="site-logo">
                            <img src="{% static 'dist/img/logo-1.png' %}" style="height: 100px; -webkit-tap-highlight-color: transparent;">
                        </a>
                    </div>

                    <div class="container col-3">
                        <div class="container justify-content-center">
                            <span class="field-content">
                                <a href="https://www.pcc.cu/es">Partido Comunista de Cuba</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="https://www.presidencia.gob.cu/es/">Sitio de la Presidencia</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="http://www.parlamentocubano.gob.cu/">Asamblea Nacional del Poder Popular</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="http://www.cubacrece.gob.cu/">Cubacrece</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="http://www.fgr.gob.cu/es">Fiscalía General de la República</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content"><a href="https://www.minint.gob.cu/">Ministerio del Interior</a>
                            </span>
                        </div>
                    </div>

                    <div class="container col-3">
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="http://www.tsp.gob.cu/es">Tribunal Supremo Popular</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="https://www.minjus.gob.cu">Ministerio de Justicia</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="http://www.minrex.gob.cu/">Ministerio de Relaciones Exteriores</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="http://www.onei.gob.cu/">Oficina Nacional de Estadística e Información</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="http://www.fidelcastro.cu">Sitio Fidel Soldado de las ideas</a>
                            </span>
                        </div>
                    </div>

                    <div class="container col-3">
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="https://www.redcuba.cu">Red C.U.B.A</a>
                            </span>
                        </div>

                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="https://www.gacetaoficial.gob.cu">Gaceta Oficial de la República de Cuba</a>
                            </span>
                        </div>
                        <div class="views-field views-field-title">
                            <span class="field-content">
                                <a href="http://www.cubadebate.cu/etiqueta/cuba/">Cubadebate</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="justify-content-center">
        <a href="#">
            <span class="fa-stack fa-4x">
                <i class="fa fa-arrow-up fa-stack-1x fa-inverse"></i>
            </span>
        </a>
        <p>Ir arriba</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="region region-footer-info">
                    <div id="block-footerinfo" class="block block-block-content block-block-content173e971f-2d0a-4c88-bc1a-ab10c05d7ca1">
                        <div class="clearfix text-formatted field field--name-body field--type-text-with-summary field--label-hidden field__item">
                            <p>Todos los derechos reservados © 2019. Contraloría General de la República de Cuba. Desarrollado por
                                <a href="http://www.uci.cu/">UCI</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

plantilla/templates/base/head.html
{% load static %}
<!--LOS LINKS DEL CSS-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>CGR</title>
    
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- IonIcons -->
    <link rel="stylesheet" href="{% static 'dist/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="{% static 'fonts/fonts_dashboard.css' %}" rel="stylesheet">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static "plugins/icheck-bootstrap/icheck-bootstrap.min.css" %} ">
    <!-- DataTables  & Plugins -->
    <link rel="stylesheet" href="{% static "lib/datatables/datatables.min.css" %} ">
    <link rel="stylesheet" href="{% static "lib/datatables/dataTables.dataTables.css" %} ">

    <link rel="stylesheet" href="{% static "dist/css/index.css" %} ">
    <link rel="stylesheet" href="{% static "dist/css/styles.css" %} ">

    <link rel="stylesheet" href="{% static "lib/bootstrap/css/bootstrap.min.css" %} ">





    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
    <!-- Bootstrap -->
    <script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <!-- AdminLTE -->
    <script src="{% static "dist/js/adminlte.js" %}"></script>
    <!-- DataTables  & Plugins -->
    <script src="{% static 'lib/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'lib/datatables/pdfmake.min.js' %}"></script>
    <script src="{% static 'lib/datatables/vfs_fonts.js' %}"></script>

    <!-- Highchart -->
    <script src="{% static 'lib/highcharts/highcharts.js' %}"></script>
    <script src="{% static 'lib/highcharts/modules/exporting.js' %}"></script>
    <script src="{% static 'lib/highcharts/modules/export-data.js' %}"></script>
    <script src="{% static 'lib/highcharts/modules/accessibility.js' %}"></script>


    <!-- Custom -->
    <script src=""></script>
    <script src="{% static "dist/js/jspdf.umd.min.js" %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static "dist/js/script.min.js" %}"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>
    <script src="{% static "dist/js/demo.js" %}"></script>
    <script src="{% static "dist/js/pages/dashboard3.js" %}"></script>
    <!-- SWEETALERT2 -->
    <script src="{% static 'dist/js/sweetalert2.js' %}"></script>

</head>

plantilla/templates/base/header.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-blue">
        <a class="navbar-brand" href="#">
            <img src="{% static 'dist/img/logo-1.png' %}" style="height: 40px;">
        </a>
        <div class="ml-auto d-flex align-items-center">
            {% if request.user.is_authenticated %}
                <div class="mr-2">
                    <a class="btn btn-outline-light" href=".">
                        {% if request.user.groups %}
                        	{{ request.user.groups.all.0.name }} |
                        {% endif %}
                        {{ request.user }}
                    </a>
                </div>
                <div>
                    <a class="btn bg-danger text-light" href="{% url 'user:logout' %}">Cerrar Sesión</a>
                </div>
            {% else %}
                <div>
                    <a class="btn btn-outline-light" href="{% url 'user:login' %}">Acceder</a>
                </div>
            {% endif %}
        </div>
    </nav>
</header>

plantilla/templates/base/scripts_alert.html
{% if data.success_message %}
    <script>
        Swal.fire({
            icon: 'success',
            title: '{{ data.success_message }}',
            showConfirmButton: false,
            timer: 3000
        });
    </script>
{% elif data.error_message %}
    <script>
        Swal.fire({
            icon: 'error',
            title: '{{ data.error_message }}',
            showConfirmButton: true,
        });
    </script>
{% endif %}
    <script>
        window.onbeforeunload = function () {
            cerrarSesion();
        };
    </script>

<script>
    {% if messages %}
        var html = '<p>';
        {% for message in messages %}
            html += '{{ message }}<br>';
        {% endfor %}
        html += '</p>';
        Swal.fire({
            icon: 'error',
            title: 'Error!',
            html: html,
        });
    {% endif %}
</script>