core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('gestion_contraloria.urls')),
    path('', include('plantilla.urls')),
]

gestion_contraloria/urls.py
from django.urls import path
from .views.dashboard import DashboardView
from .views.organizacion_views import *
from .views.reporte_views import ReporteListView, ReporteCreateView, ReporteUpdateView, ReporteDeleteView

app_name = 'gestion_contraloria'
urlpatterns = [
    ##################################### dashboard #####################################
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    ##################################### organization #####################################
    path('organization_list/', OrganizacionListView.as_view(), name='organization_list'),
    path('organization_update/', OrganizacionUpdateView.as_view(), name='organization_update'),

    ##################################### report #####################################
    path('report_list/', ReporteListView.as_view(), name='report_list'),
    path('report_create/', ReporteCreateView.as_view(), name='report_create'),
    path('report_update/<int:pk>/', ReporteUpdateView.as_view(), name='report_update'),
    path('report_delete/', ReporteDeleteView.as_view(), name='report_delete'),
]

gestion_contraloria/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from datetime import datetime

class Organizacion(models.Model):
    
    nombre = models.CharField(max_length=50, null=False, unique=True)
    descripcion = models.CharField(max_length=250,)
    direccion = models.CharField(max_length=250,)
    telefono = models.CharField(max_length=20,)

    en_supervision = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Organización"
        verbose_name_plural = "Organizaciones"

class Reporte(models.Model):

    ingresos_anuales = models.IntegerField()
    gastos_de_capital = models.IntegerField()
    proyectos = models.IntegerField()
    deudas_actuales = models.IntegerField()
    personal = models.IntegerField()
    costos_de_personal = models.IntegerField()
    fecha = models.DateField(auto_now=True)

    organizacion_id = models.ForeignKey(Organizacion, on_delete=models.SET_NULL, null=True, blank=True)
    user_id = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)
    user_name = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = "Reporte"
        verbose_name_plural = "Reportes"

gestion_contraloria/forms.py
from django.forms import ModelForm
from .models import *


class ReportForm(ModelForm):
    class Meta:
        model = Reporte
        exclude = ['user_id']

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)

        return data

gestion_contraloria/views/dashboard.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import Reporte
from datetime import datetime

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/dashboard.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return redirect('/admin/')
        user = request.user
        if user.groups.all() and str(user.groups.all()[0]) == 'Auditor':
            return redirect('gestion_contraloria:organization_list')
        return super().dispatch(request, *args, **kwargs)

    def get_reports_year_month(self, year):
        data = []
        try:
            for m in range(1, 12):
                reportes = Reporte.objects.filter(fecha__year=year, fecha__month=m).count()
                data.append(reportes)
        except:
            pass
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = self.request.GET.get('year', datetime.now().year)

        context['selected_year'] = int(year)
        context['reportes_anno_mes'] = self.get_reports_year_month(year)
        context['years'] = range(datetime.now().year - 5, datetime.now().year + 1)
        return context

gestion_contraloria/views/organizacion_views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from ..mixins import IsSuperuserMixin, ValidatedPermissionRequiredMixin
from ..models import *

class OrganizacionListView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, ListView):
    model = Organizacion
    template_name = 'dashboard/dashboard.html'
    permission_required = 'view_organizacion'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        organizacion_list = Organizacion.objects.filter(
            en_supervision=None
        )
        user_organizacion_list = Organizacion.objects.filter(
            en_supervision=self.request.user
        )
        organizacion_reportes_list = [
            [organizacion, Reporte.objects.filter(organizacion_id=organizacion.id).count()]
            for organizacion in user_organizacion_list
        ]
        title = 'Organizaciones' if len(user_organizacion_list) > 1 else 'Organización'

        context = super().get_context_data(**kwargs)
        context['title_list'] = title
        context['title'] = 'Añadir Organización'
        context['entity'] = Organizacion
        context['organizacion_list'] = organizacion_list
        context['user_organizacion_list'] = organizacion_reportes_list
        context['action_add'] = 'add'
        context['action_update'] = 'update'
        context['message'] = 'Sin organizaciones para auditar'
        context['data'] = self.request.session.pop('data', None)

        return context


class OrganizacionUpdateView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, View):
    model = Organizacion
    template_name = 'dashboard/dashboard.html'
    permission_required = 'change_organizacion'
    success_url = reverse_lazy('gestion_contraloria:organization_list')
    url_redirect = success_url

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            if action == 'update':
                organizacion = Organizacion.objects.get(pk=int(self.request.POST['id']))

                if organizacion:
                    if organizacion.en_supervision:
                        organizacion.en_supervision = None
                        request.session['data'] = {
                            'success_message': 'La organización se ha eliminado con éxito.',
                        }
                    else:
                        organizacion.en_supervision = self.request.user
                        request.session['data'] = {
                            'success_message': 'La organización se ha añadido con éxito.',
                        }

                    organizacion.save()
                    data['form_is_valid'] = True
                else:
                    data['error'] = 'No hay ninguna organización'
            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Exception as e:
            data['error'] = str(e)
            print(data['error'])

        if data['form_is_valid']:

            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

gestion_contraloria/views/reporte_views.py
import requests
from django.contrib.auth.models import Group
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, View, CreateView, DeleteView
from ..mixins import IsSuperuserMixin, ValidatedPermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import *
from ..forms import ReportForm


class ReporteListView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, ListView):
    model = Reporte
    template_name = 'dashboard/dashboard.html'
    permission_required = 'view_reporte'
    context_object_name = 'user_report_list'

    user_group = None


    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    def get_queryset(self):
        user = self.request.user

        grupo_gerente = Group.objects.get(name='Gerente')
        grupo_auditor = Group.objects.get(name='Auditor')

        if grupo_gerente in user.groups.all():
            return Reporte.objects.all()

        elif grupo_auditor in user.groups.all():
            return Reporte.objects.filter(user_id=user)

        else:
            return Reporte.objects.none()


    def get_context_data(self, **kwargs):
        if self.request.user.groups.all():
            self.user_group = self.request.user.groups.all()[0]

        context = super().get_context_data(**kwargs)
        context['title_list'] = 'Reporte(s)'
        context['title'] = 'Añadir Reporte'
        context['entity'] = Reporte
        context['user_group'] = self.user_group
        context['action_add'] = 'add'
        context['action_update'] = 'update'
        context['message'] = 'No se ha creado ningún reporte'
        context['data'] = self.request.session.pop('data', None)

        return context


class ReporteCreateView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, CreateView):
    model = Reporte
    template_name = 'dashboard/dashboard.html'
    permission_required = 'add_reporte'
    form_class = ReportForm
    success_url = reverse_lazy('gestion_contraloria:report_list')

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False
        try:
            action = request.POST['action_add']
            if action == 'add':
                form = self.get_form()
                print(request.POST)
                if form.is_valid():
                    form.instance.user_id = self.request.user
                    form.instance.user_name = self.request.user.username
                    form.save()
                    data['form_is_valid'] = True
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado ninguna acción!'

        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El reporte ha sido creado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)


class ReporteUpdateView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, UpdateView):
    model = Reporte
    template_name = 'dashboard/dashboard.html'
    permission_required = 'change_reporte'
    form_class = ReportForm
    success_url = reverse_lazy('gestion_contraloria:report_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            print(request.POST)
            if action == 'update':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    data['form_is_valid'] = True

                else:
                    data['error'] = form.errors

            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El reporte ha sido actualizado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)


class ReporteDeleteView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, View):
    model = Reporte
    success_url = reverse_lazy('gestion_contraloria:report_list')
    template_name = 'dashboard/dashboard.html'
    permission_required = 'delete_reporte'

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            if action == 'update':
                report = Reporte.objects.get(pk=int(request.POST['report_id']))

                if report:
                    if report.user_id == request.user:
                        report.user_id = None
                        request.session['data'] = {
                            'success_message': 'El reporte se ha eliminado con éxito.',
                        }
                        print(request.POST['report_id'])
                        report.save()
                        data['form_is_valid'] = True
                else:
                    data['error'] = 'No hay ningún reporte'
            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Exception as e:
            data['error'] = str(e)
            print(data['error'])

        if data['form_is_valid']:

            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

gestion_contraloria/templates/dashboard/auditor_dashboard.html
{% if request.path == "/organization_list/"%}
   {% include 'organizacion.html' %}
{% elif request.path == "/report_list/" %}
    {% include 'reporte/reporte_list.html' %}
{% endif %}

gestion_contraloria/templates/dashboard/dashboard.html
{% extends "base/body.html" %}
{% load static %}

{% block content %}
<div class="wrapper">
  <!-- Main Sidebar Container -->

  {% include 'dashboard/sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ title_list }}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'gestion_contraloria:dashboard' %}">Menú Principal</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div> 
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="container p-3">
    {% if request.user.groups.all %}
        {% with request.user.groups.all.0 as group %}
            
        	{% if group.name == 'Auditor' %}
                {% include 'dashboard/auditor_dashboard.html' %}
            {% elif group.name == 'Gerente' %}
                {% include 'dashboard/gerente_dashboard.html' %}
            {% endif %}
        {% endwith %}
        
    {% else %}    
        No tiene un rol definido
    {% endif %}
         
    </div>
    
      <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
{% endblock content %}

gestion_contraloria/templates/dashboard/gerente_dashboard.html
<!-- Main content -->
{% if request.path == "/dashboard/" %}
   {% include 'graficas.html' %}
{% elif request.path == "/report_list/" %}
    {% include 'reporte/reporte_list.html' %}
{% endif %}

gestion_contraloria/templates/dashboard/sidebar.html
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview {% if 'dashboard' in request.path or 'organization_list' in request.path or 'report_list' in request.path %}menu-open{% endif %}">
                    <a href="#" class="nav-link {% if 'dashboard' in request.path or 'organization_list' in request.path or 'report_list' in request.path %}active{% endif %}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Menú Principal
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        {% if request.user.groups.all %}
                            {% with request.user.groups.all.0 as group %}
                                {% if group.name == 'Gerente' %}
                                    <li class="nav-item">
                                        <a href="{% url 'gestion_contraloria:dashboard' %}" class="nav-link {% if 'dashboard' in request.path %}active{% endif %}">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Datos generales</p>
                                        </a>
                                    </li>
                                {% elif group.name == 'Auditor' %}
                                    <li class="nav-item">
                                        <a href="{% url 'gestion_contraloria:organization_list' %}" class="nav-link {% if 'organization_list' in request.path %}active{% endif %}">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Organizaciones</p>
                                        </a>
                                    </li>
                                {% endif %}
                            {% endwith %}
                        {% endif %}
                        <li class="nav-item">
                            <a href="{% url 'gestion_contraloria:report_list' %}" class="nav-link {% if 'report_list' in request.path %}active{% endif %}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Reportes</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->