core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('gestion_contraloria.urls')),
    path('', include('plantilla.urls')),
]

gestion_contraloria/urls.py
from django.urls import path
from .views.dashboard import DashboardView
from .views.organizacion_views import *
from .views.reporte_views import ReporteListView, ReporteCreateView, ReporteUpdateView, ReporteDeleteView

app_name = 'gestion_contraloria'
urlpatterns = [
    ##################################### dashboard #####################################
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    ##################################### organization #####################################
    path('organization_list/', OrganizacionListView.as_view(), name='organization_list'),
    path('organization_update/', OrganizacionUpdateView.as_view(), name='organization_update'),

    ##################################### report #####################################
    path('report_list/', ReporteListView.as_view(), name='report_list'),
    path('report_create/', ReporteCreateView.as_view(), name='report_create'),
    path('report_update/<int:pk>/', ReporteUpdateView.as_view(), name='report_update'),
    path('report_delete/', ReporteDeleteView.as_view(), name='report_delete'),
]

gestion_contraloria/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from datetime import datetime

class Organizacion(models.Model):
    
    nombre = models.CharField(max_length=50, null=False, unique=True)
    descripcion = models.CharField(max_length=250,)
    direccion = models.CharField(max_length=250,)
    telefono = models.CharField(max_length=20,)

    en_supervision = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Organización"
        verbose_name_plural = "Organizaciones"

class Reporte(models.Model):

    ingresos_anuales = models.IntegerField()
    gastos_de_capital = models.IntegerField()
    proyectos = models.IntegerField()
    deudas_actuales = models.IntegerField()
    personal = models.IntegerField()
    costos_de_personal = models.IntegerField()
    fecha = models.DateField(auto_now=True)

    organizacion_id = models.ForeignKey(Organizacion, on_delete=models.SET_NULL, null=True, blank=True)
    user_id = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)
    user_name = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = "Reporte"
        verbose_name_plural = "Reportes"

gestion_contraloria/forms.py
from django.forms import ModelForm
from .models import *


class ReportForm(ModelForm):
    class Meta:
        model = Reporte
        exclude = ['user_id']

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)

        return data

gestion_contraloria/views/dashboard.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import Reporte
from datetime import datetime

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/dashboard.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return redirect('/admin/')
        user = request.user
        if user.groups.all() and str(user.groups.all()[0]) == 'Auditor':
            return redirect('gestion_contraloria:organization_list')
        return super().dispatch(request, *args, **kwargs)

    def get_reports_year_month(self, year):
        data = []
        try:
            for m in range(1, 12):
                reportes = Reporte.objects.filter(fecha__year=year, fecha__month=m).count()
                data.append(reportes)
        except:
            pass
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = self.request.GET.get('year', datetime.now().year)

        context['selected_year'] = int(year)
        context['reportes_anno_mes'] = self.get_reports_year_month(year)
        context['years'] = range(datetime.now().year - 5, datetime.now().year + 1)
        return context

gestion_contraloria/views/organizacion_views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from ..mixins import IsSuperuserMixin, ValidatedPermissionRequiredMixin
from ..models import *

class OrganizacionListView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, ListView):
    model = Organizacion
    template_name = 'dashboard/dashboard.html'
    permission_required = 'view_organizacion'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        organizacion_list = Organizacion.objects.filter(
            en_supervision=None
        )
        user_organizacion_list = Organizacion.objects.filter(
            en_supervision=self.request.user
        )
        organizacion_reportes_list = [
            [organizacion, Reporte.objects.filter(organizacion_id=organizacion.id).count()]
            for organizacion in user_organizacion_list
        ]
        title = 'Organizaciones' if len(user_organizacion_list) > 1 else 'Organización'

        context = super().get_context_data(**kwargs)
        context['title_list'] = title
        context['title'] = 'Añadir Organización'
        context['entity'] = Organizacion
        context['organizacion_list'] = organizacion_list
        context['user_organizacion_list'] = organizacion_reportes_list
        context['action_add'] = 'add'
        context['action_update'] = 'update'
        context['message'] = 'Sin organizaciones para auditar'
        context['data'] = self.request.session.pop('data', None)

        return context


class OrganizacionUpdateView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, View):
    model = Organizacion
    template_name = 'dashboard/dashboard.html'
    permission_required = 'change_organizacion'
    success_url = reverse_lazy('gestion_contraloria:organization_list')
    url_redirect = success_url

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            if action == 'update':
                organizacion = Organizacion.objects.get(pk=int(self.request.POST['id']))

                if organizacion:
                    if organizacion.en_supervision:
                        organizacion.en_supervision = None
                        request.session['data'] = {
                            'success_message': 'La organización se ha eliminado con éxito.',
                        }
                    else:
                        organizacion.en_supervision = self.request.user
                        request.session['data'] = {
                            'success_message': 'La organización se ha añadido con éxito.',
                        }

                    organizacion.save()
                    data['form_is_valid'] = True
                else:
                    data['error'] = 'No hay ninguna organización'
            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Exception as e:
            data['error'] = str(e)
            print(data['error'])

        if data['form_is_valid']:

            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

gestion_contraloria/views/reporte_views.py
import requests
from django.contrib.auth.models import Group
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, View, CreateView, DeleteView
from ..mixins import IsSuperuserMixin, ValidatedPermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import *
from ..forms import ReportForm


class ReporteListView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, ListView):
    model = Reporte
    template_name = 'dashboard/dashboard.html'
    permission_required = 'view_reporte'
    context_object_name = 'user_report_list'

    user_group = None


    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    def get_queryset(self):
        user = self.request.user

        grupo_gerente = Group.objects.get(name='Gerente')
        grupo_auditor = Group.objects.get(name='Auditor')

        if grupo_gerente in user.groups.all():
            return Reporte.objects.all()

        elif grupo_auditor in user.groups.all():
            return Reporte.objects.filter(user_id=user)

        else:
            return Reporte.objects.none()


    def get_context_data(self, **kwargs):
        if self.request.user.groups.all():
            self.user_group = self.request.user.groups.all()[0]

        context = super().get_context_data(**kwargs)
        context['title_list'] = 'Reporte(s)'
        context['title'] = 'Añadir Reporte'
        context['entity'] = Reporte
        context['user_group'] = self.user_group
        context['action_add'] = 'add'
        context['action_update'] = 'update'
        context['message'] = 'No se ha creado ningún reporte'
        context['data'] = self.request.session.pop('data', None)

        return context


class ReporteCreateView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, CreateView):
    model = Reporte
    template_name = 'dashboard/dashboard.html'
    permission_required = 'add_reporte'
    form_class = ReportForm
    success_url = reverse_lazy('gestion_contraloria:report_list')

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False
        try:
            action = request.POST['action_add']
            if action == 'add':
                form = self.get_form()
                print(request.POST)
                if form.is_valid():
                    form.instance.user_id = self.request.user
                    form.instance.user_name = self.request.user.username
                    form.save()
                    data['form_is_valid'] = True
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha ingresado ninguna acción!'

        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El reporte ha sido creado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)


class ReporteUpdateView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, UpdateView):
    model = Reporte
    template_name = 'dashboard/dashboard.html'
    permission_required = 'change_reporte'
    form_class = ReportForm
    success_url = reverse_lazy('gestion_contraloria:report_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            print(request.POST)
            if action == 'update':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    data['form_is_valid'] = True

                else:
                    data['error'] = form.errors

            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Exception as e:
            data['error'] = str(e)

        if data['form_is_valid']:
            request.session['data'] = {
                'success_message': 'El reporte ha sido actualizado con éxito.'}
            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)


class ReporteDeleteView(LoginRequiredMixin, ValidatedPermissionRequiredMixin, View):
    model = Reporte
    success_url = reverse_lazy('gestion_contraloria:report_list')
    template_name = 'dashboard/dashboard.html'
    permission_required = 'delete_reporte'

    def post(self, request, *args, **kwargs):
        data = {}
        data['form_is_valid'] = False

        try:
            action = request.POST['action_update']
            if action == 'update':
                report = Reporte.objects.get(pk=int(request.POST['report_id']))

                if report:
                    if report.user_id == request.user:
                        report.user_id = None
                        request.session['data'] = {
                            'success_message': 'El reporte se ha eliminado con éxito.',
                        }
                        print(request.POST['report_id'])
                        report.save()
                        data['form_is_valid'] = True
                else:
                    data['error'] = 'No hay ningún reporte'
            else:
                data['error'] = 'No ha ingresado ninguna acción'
        except Exception as e:
            data['error'] = str(e)
            print(data['error'])

        if data['form_is_valid']:

            return redirect(self.success_url)
        else:
            request.session['data'] = {
                'error_message': data['error']}
            return redirect(self.success_url)

gestion_contraloria/templates/graficas.html
<div class="content">
  <div class="container-fluid">
    <div class="col">
      <div class="col-lg-12">
        <form id="yearForm" method="GET" action="">
          <label for="yearSelect">Seleccionar año:</label>
          <select id="yearSelect" name="year" class="form-control">
            {% for y in years %}
              <option value="{{ y }}" {% if y == selected_year %}selected{% endif %}>{{ y }}</option>
            {% endfor %}
          </select>
        </form>
      </div>

      <div class="col-lg-12 graf-container" style="margin-bottom: 20px;">
        <div id="graf_bar"></div>
      </div>

      <div class="col-lg-12 graf-container">
        <div id="graf_pastel"></div>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById('yearSelect').addEventListener('change', function() {
    document.getElementById('yearForm').submit();
  });

  Highcharts.chart('graf_bar', {
    chart: {
      type: 'column',
      zooming: {
        type: 'y'
      }
    },
    title: {
      text: 'Organizaciones auditadas',
      style: {
        backgroundColor: '#356fdc',
        padding: '10px',
        borderRadius: '5px'
      }
    },
    subtitle: {
      text: 'Gráfica de auditorias realizadas a las organizaciones en cada mes'
    },
    xAxis: {
      categories: [
        'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio',
        'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
      ],
      title: {
        text: null
      },
      accessibility: {
        description: 'Organizaciones'
      }
    },
    yAxis: {
      min: 0,
      tickInterval: 2,
      title: {
        text: 'Auditorias'
      },
      labels: {
        overflow: 'justify',
        format: '{value}'
      }
    },
    plotOptions: {
      column: {
        dataLabels: {
          enabled: true,
          format: '{y}'
        }
      }
    },
    tooltip: {
      valueSuffix: ' auditoria(s)',
      stickOnContact: true,
      backgroundColor: 'rgba(255, 255, 255, 0.93)'
    },
    legend: {
      enabled: false
    },
    series: [
      {
        name: 'Auditoria(s) realizada(s) a la organización',
        data: {{ reportes_anno_mes|safe }},
        borderColor: '#5997DE'
      }
    ]
  });

  Highcharts.chart('graf_pastel', {
    colors: ['#01BAF2', '#f6fa4b', '#FAA74B', '#baf201', '#f201ba'],
    chart: {
      type: 'pie'
    },
    title: {
      text: 'Organizaciones',
      style: {
        backgroundColor: '#f8f9fa',
        padding: '10px',
        borderRadius: '5px'
      }
    },
    tooltip: {
      valueSuffix: '%'
    },
    subtitle: {
      text: 'Representación de las organizaciones auditadas y sin auditar'
    },
    plotOptions: {
      pie: {
        allowPointSelect: true,
        cursor: 'pointer',
        dataLabels: {
          enabled: true,
          format: '{point.name}: {point.percentage:.1f}%'
        },
        showInLegend: false
      }
    },
    series: [
      {
        name: 'Organizaciones',
        colorByPoint: true,
        data: [
          {
            name: 'Auditadas',
            y: 55.02
          },
          {
            name: 'Sin auditar',
            y: 15.5
          }
        ]
      }
    ]
  });
</script>

gestion_contraloria/templates/organizacion.html
{% block content %}
<div class="container justify-content-center">
    <div class="container pb-3">
        <a type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#orgModal">Añadir Organización</a>
        <!-- Modal Org -->
        <div class="modal fade" id="orgModal" tabindex="-1" role="dialog" aria-labelledby="orgModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="orgModalLabel">{{ title }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="orgFormulario" method="POST" action="{% url 'gestion_contraloria:organization_update' %}">
                            {% csrf_token %}
                            <input type="hidden" name="action_update" value="{{ action_update }}">
                            <div class="form-group">
                                <label for="seleccion">Selecciona una opción:</label>
                                <select class="form-control" id="org_seleccion" name="id">
                                    {% for object in organizacion_list %}
                                        <option value="{{ object.id }}">{{ object.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary" id="orgbtnAceptar">Aceptar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if user_organizacion_list %}
        <div class="row">
            {% for user_organizacion in user_organizacion_list %}
                <div class="col-md-4 mb-4">
                    <div class="card text-center">
                        <div class="card-header bg-primary">
                            {{ user_organizacion.0.nombre }}
                        </div>
                        <div class="card-body">
                            <p class="card-text">Descripción: {{ user_organizacion.0.descripcion }}</p>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <i class="fas fa-map-marker-alt"></i> {{ user_organizacion.0.direccion }}
                                </li>
                                <li class="list-group-item">
                                    <i class="fas fa-phone-alt"></i> {{ user_organizacion.0.telefono }}
                                </li>
                                <li class="list-group-item">
                                    <i class="fas fa-phone-alt"></i> {{ user_organizacion.0.id }}
                                </li>
                            </ul>
                        </div>
                        <div class="card-footer text-muted">
                            <div class="row col-12 px-2">
                                <!-- Modal Auditar -->
                                <a href="#" class="btn btn-warning col-6 mb-2" data-toggle="modal" data-target="#crearReporteModal" data-id="{{ user_organizacion.0.id }}">Auditar</a>
                                <div class="modal fade" id="crearReporteModal" aria-labelledby="crearReporteModalLabel" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="crearReporteModalLabel">Reporte</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <form action="{% url 'gestion_contraloria:report_create' %}" method="post">
                                                <div class="modal-body">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="organizacion_id" value="">
                                                    <input type="hidden" name="action_add" value="{{ action_add }}">
                                                    <!-- Campos del formulario -->
                                                    <div class="form-group">
                                                        <input type="number" name="ingresos_anuales" id="id_ingresos_anuales" class="form-control" placeholder="Ingresos Anuales" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="number" name="gastos_de_capital" id="id_gastos_de_capital" class="form-control" placeholder="Gastos de Capital" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="number" name="proyectos" id="id_proyectos" class="form-control" placeholder="Proyectos" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="number" name="deudas_actuales" id="id_deudas_actuales" class="form-control" placeholder="Deudas Actuales" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="number" name="personal" id="id_personal" class="form-control" placeholder="Personal" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="number" name="costos_de_personal" id="id_costos_de_personal" class="form-control" placeholder="Costos de Personal" required>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                                    <button type="submit" class="btn btn-primary">Guardar Reporte</button>
                                                </div>
                                            </form>

                                        </div>
                                    </div>
                                </div>
                                <a type="button" class="btn btn-danger col-6 mb-2" data-toggle="modal" data-target="#orgQuitModal">
                                    <i class="fas fa-trash"></i>
                                </a>
                                <!-- Modal Org -->
                                <div class="modal fade" id="orgQuitModal" tabindex="-1" role="dialog" aria-labelledby="orgQuitModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="orgQuitModalLabel">{{ title }}</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <form id="orgQuitFormulario" method="POST" action="{% url 'gestion_contraloria:organization_update' %}">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="action_update" value="{{ action_update }}">
                                                    <input type="hidden" name="id" value="{{ user_organizacion.0.id }}">
                                                    <p>¿Desea quitar la organización?</p>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                                        <button type="submit" class="btn btn-danger" id="orgbtnAceptar">Sí</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <p>{{ user_organizacion.1 }} Auditoría(s) realizada(s)</p>
                            </div>
                        </div>
                    </div>
                </div>  
            {% endfor %}
        </div>
    {% else %}
        <p>{{ message }}</p>
    {% endif %}
</div>

<script>
    $('#crearReporteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget); // Botón que activó el modal
        var orgId = button.data('id'); // Extraer la información del atributo data-id

        var modal = $(this);
        modal.find('input[name="organizacion_id"]').val(orgId);
    });
</script>
{% endblock content %}